# Dependencies
markdown:         redcarpet
highlighter:      rouge

# # Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Swyng
tagline:          'A Jekyll theme'
description:      'A simpler classwork interface.'
url:              https://mediocrecode.github.io/4800TermProject/
baseurl:          https://mediocrecode.github.io/4800TermProject/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
